### ISSUE TITLE
Part 3: Reflect & Documentation

### ISSUE THREAD

**Issue by yunchaecho2** [CultureAsData-UIUC/is310-fall-2024-group-6#14]

**Comment by frangara** [comment]
# Documenting the data
The structure of our dataset is the basic format that Spotify uses as well as our subjective column that we added. Using this we have Song Title, Artist, Album, Genre, Release Year, Mood While listening, Personal Connection, and Subjective Genre. These are topics that give us more detail when it comes to how our group members feel when listening to these songs. The columns that we added as our new columns take in our own feelings when it comes to interacting with the data. Looking at it we can display emotional state, personal significance or memories associated, and even a recategorized column that each group member used for their specific interpretation. 

The data types show normal classification that is very specific and Spotify curated. The additional data types that we added give a personal sense and are more specific to our group and data curation. This allows us to have quality data when it comes to creating our own dataset. Given that we were able to provide a dataset, we were able to complete it further using our own interpretations and feelings with subjectiveness. 

Song Title | Artist | Album | Genre | Release Year | Mood While Listening | Personal Connection | Subjective Genre
-- | -- | -- | -- | -- | -- | -- | --
Blinding Lights | The Weeknd | After Hours | Synthwave | 2020 | Uplifted | Reminds me of late-night drives | Retro Pop
Levitating | Dua Lipa | Future Nostalgia | Pop | 2020 | Energetic | Played at my friend's wedding party | Disco
Peaches | Justin Bieber | Justice | R&B | 2021 | Chill | My favorite track during summer | R&B/Pop Fusion
Good 4 U | Olivia Rodrigo | SOUR | Pop Punk | 2021 | Angry | Reminds me of a breakup I went through | Emo Pop
Watermelon Sugar | Harry Styles | Fine Line | Pop Rock | 2019 | Happy | Played during a memorable beach day | Soft Rock
drivers license | Olivia Rodrigo | SOUR | Pop | 2021 | Heartbroken | Makes me think of my high school relationship | Emotional Ballad
Montero | Lil Nas X | Montero | Hip-Hop | 2021 | Empowering | Reminds me of my coming-out moment | Hip-Hop/Pop Crossover
Stay | The Kid LAROI | F*CK LOVE | Pop | 2021 | Nostalgic | Played on repeat during summer | Pop
Save Your Tears | The Weeknd | After Hours | Synthwave | 2020 | Reflective | Makes me think about past regrets | Synthpop
Heat Waves | Glass Animals | Dreamland | Indie | 2020 | Dreamy | Reminds me of a late summer night with friends | Chillwave

# Reflecting on The Data

We determined as a group that creating a personal connection and subjective genre off of that connection will allow our data to be more curated towards us. This not only makes our dataset one that is unique to our group, but it also allows us to be able to provide more personal connections based off of our groups responses. The personal connection column stays consistent with sharing memories of how each song affects each group member following the format of a personal connection or memory in it.

We determined to collect data from Spotify using the Spotify API and used it to collect public datasets. This was so that we would not violate anything such as private data or licensing errors. This allowed us to obtain the data cleanly as well as use it to provide the necessary transformations that we used on it to curate our own dataset.

When it comes to looking back at the platform dynamics, there can be some issues when it comes to data access. Wanting to get bulk data access, you would have to face restrictions that affect how we can retrieve data. Things such as data retrieval, user personal data, and dataset limits there are restrictions that occur when wanting to retrieve a lot of data. In general, Spotify restrictions can affect data retrieval for research.

When it comes to legal and ethical considerations that can arise when creating this dataset there are a lot of aspects. The first that comes to mind is copyright with media. Things such as musical works and artists are things that come up music related things. This is because Spotify is a paid platform where you can stream music, therefore this is a licensing thing with artists and music labels. Another thing that arose was private user data. Things such as accessing user information (private playlists, user data, images) are things that can be done with Spotify.
